### ISSUE TITLE
JS Backend: v0.6.0: Wrong generation of constructor invocation for @JTranscNativeName

### ISSUE THREAD

**Issue by marciodel** [jtransc/jtransc#134]
Hi, 

   I'm using @JTranscNativeName to implement Promise. Its constructor takes an argument, but the invocation is being generated without the argument. 

```
	tA0 = ((new tests_UnionTest$1()));
	fA0 = tA0;
	(tA0)["tests.UnionTest$1<init>()V"]();
	lA1 = fA0;
	tA1 = ((new tests_UnionTest$2()));
	fA0 = tA1;
	(tA1)["tests.UnionTest$2<init>()V"]();
	lA2 = fA0;
	tA2 = ((new Promise()));
	fA0 = tA2;
	(tA2)["<init>"]((lA1));
	(fA0).then((lA2));

```

The Promise class:

```
@com.jtransc.annotation.JTranscNativeName(value = "Promise")
public class Promise<T> implements elemental2.promise.IThenable<T> {
    public Promise(elemental2.promise.Promise.PromiseExecutorCallbackFn<T> executor) {
    }
//.......
}

```

Thanks!

**Comment by soywiz** [comment]
The ASM2 backend tried to fix this. I can recheck whether it is possible to do with ASM1 backend doing some fixes.
The problem here is that JVM allocates memory for an object and later does the constructor. Like this:

```
NEW
DUP
PUSH_ARGUMENTS
CALL_CONSTRUCTOR
```

```
tA2 = ((new Promise())); // NEW
fA0 = tA2;               // ARGUMENTS
(tA2)["<init>"]((lA1));  // CONSTRUCTOR
```

In some cases I'm able to merge it, and in those cases it generates it properly. But the current backend even when works for normal cases, fails like this and generate some ugly code.

In JS and other targets without gotos, there are two issues: temporal variables & while+switch (needs to work on a relooper like emscripten does).

My plan was to work on this issues on 0.7.0. But I will check if I can merge allocation+construction better in 0.6.x so you can use it already.

My current workaround is something like:
```
public class PromiseUtils {
    //@JtranscMethodBody(target = "js", value = "return new Promise(p0);")
    @JtranscCallSiteBody(target = "js", value = "new Promise(#0)") // or you can use this too to avoid extra function
    static public Promise create(JsDynamic arg);
}
```

**Comment by marciodel** [comment]
I'll use the workaround! Thanks!

**Comment by marciodel** [comment]
When trying this solution, I've found a regression bug.

```
java.lang.NoSuchMethodError: kotlin.text.StringsKt.toIntOrNull(Ljava/lang/String;)Ljava/lang/Integer;

        at com.jtransc.gen.common.CommonGenerator$genExprCallBa
se$out$1.invoke(CommonGenerator.kt:570)
 ....
```
If I change to 0.5.16 the solution works.

**Comment by soywiz** [comment]
Which gradle version are you using?

**Comment by marciodel** [comment]
Gradle 3.4.1

**Comment by soywiz** [comment]
It's a pain. Because I want to use Kotlin 1.1. But since they included Kotlin 1.0 for `gradle-script-kotlin`, classpath sometimes uses 1.0 and causes this kind of errors. They are using kotlin 1.1 since gradle 3.5. I have two options: roll back to Kotlin 1.0 or drop support for gradle version that started including gradle-script-kotlin until 1.1 (with previous versions should work well too).
I have problems with Gradle 3.5. But they are not going to release 3.5.1, but 4.0 directly.

I have tried to not use toIntNull in this commit ( https://github.com/jtransc/jtransc/commit/6d8bba6f430d004e662678a4b3087128813361a9 ) a few minutes ago. But it is pretty easy to add regressions and use new APIs from Kotlin 1.1

**Comment by marciodel** [comment]
I've changed to gradle 3.5 and it is working.
